### ISSUE TITLE
[Module] Player/Emotion

### ISSUE THREAD

**Issue by katopz** [digithun/clogii-mobile#15]
- [x] Can add reaction to clog
- [x] Can add reaction to episode

### View
![emotion](https://cloud.githubusercontent.com/assets/24914167/24443294/4bda0212-148c-11e7-9aaa-163b2f267ae9.png)

![emotion](https://cloud.githubusercontent.com/assets/24914167/21889981/1ec56bbe-d8fe-11e6-8613-0a88575a73c2.jpg)

**Comment by korrio** [comment]
Reaction (Facebook)
