### ISSUE TITLE
[react-native] Upgrade to react-native 0.37 

### ISSUE THREAD

**Issue by ArtNattapat** [digithun/clogii-mobile#27]
- [x] can compile with XCode 8.1+
- [x] ~~[IOS] can login with facebook after upgrade~~ ref : #29 
- [x] can compile Android version
- [x] [android] can login with facebook after upgrade
- [x] upgrade or remove npm-shrinkwrap

**Comment by katopz** [comment]
ref : https://github.com/digithun/clogii-mobile/issues/29
